// angular-ui/src/app/auth/login.component.ts
import { HttpClient } from '@angular/common/http';
import { Component } from '@angular/core';
import { FormControl, ReactiveFormsModule, Validators } from '@angular/forms';
import { DomSanitizer, SafeUrl } from '@angular/platform-browser';
import { Observable, map } from 'rxjs';
import { UserService } from './user.service';
import { baseUri } from '../app.config';
import { Router } from '@angular/router';
import { CommonModule } from '@angular/common';

enum LoginExperience {
  IFRAME,
  DEFAULT,
}

interface LoginOptionDto {
  label: string;
  loginUri: string;
  isSameAuthority: boolean;
}

function loginOptions(http: HttpClient): Observable<Array<LoginOptionDto>> {
  return http
    .get('/login-options')
    .pipe(map((dto: any) => dto as LoginOptionDto[]));
}

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule],
  template: `<span>
      <select [formControl]="selectedLoginExperience" [disabled]="!isLoginEnabled">
        <option *ngFor="let le of loginExperiences">
          {{ loginExperienceLabel(le) }}
        </option>
      </select>
      <button (click)="login()"  [disabled]="!isLoginEnabled">Login</button>
    </span>
    <div
      class="modal-overlay"
      *ngIf="isLoginModalDisplayed && !isAuthenticated"
      (click)="isLoginModalDisplayed = false"
    >
      <div class="modal">
        <iframe
          [src]="iframeSrc"
          frameborder="0"
          (load)="onIframeLoad($event)"
        ></iframe>
        <button class="close-button" (click)="isLoginModalDisplayed = false">
          Discard
        </button>
      </div>
    </div>`,
  styles: `.modal-overlay {
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background-color: rgba(0, 0, 0, 0.5);
    display: flex;
    justify-content: center;
    align-items: center;
    z-index: 9999;
  }

  .modal {
    background-color: #fff;
    padding: 20px;
    border-radius: 5px;
    position: relative;
    width: 100%;
    max-width: 800px;
  }

  .modal iframe {
    width: 100%;
    height: 600px;
    border: none;
  }`,
})
export class LoginComponent {
  isLoginModalDisplayed = false;
  iframeSrc?: SafeUrl;
  loginExperiences: LoginExperience[] = [];
  selectedLoginExperience = new FormControl<LoginExperience | null>(null, [
    Validators.required,
  ]);

  private loginUri?: string;

  constructor(
    http: HttpClient,
    private user: UserService,
    private router: Router,
    private sanitizer: DomSanitizer
  ) {
    loginOptions(http).subscribe((opts) => {
      if (opts.length) {
        this.loginUri = opts[0].loginUri;
        if (opts[0].isSameAuthority) {
          this.loginExperiences.push(LoginExperience.IFRAME);
        }
        this.loginExperiences.push(LoginExperience.DEFAULT);
        this.selectedLoginExperience.patchValue(this.loginExperiences[0]);
      }
    });
  }

  get isLoginEnabled(): boolean {
    return (
      this.selectedLoginExperience.valid && !this.user.current.isAuthenticated
    );
  }

  get isAuthenticated(): boolean {
    return this.user.current.isAuthenticated;
  }

  login() {
    if (!this.loginUri) {
      return;
    }

    const url = new URL(this.loginUri);
    url.searchParams.append(
      'post_login_success_uri',
      `${baseUri}${this.router.url}`
    );
    const loginUrl = url.toString();

    if (this.selectedLoginExperience.value === LoginExperience.IFRAME) {
      this.iframeSrc = this.sanitizer.bypassSecurityTrustResourceUrl(loginUrl);
      this.isLoginModalDisplayed = true;
    } else {
      window.location.href = loginUrl;
    }
  }

  onIframeLoad(event: any) {
    if (!!event.currentTarget.src) {
      this.user.refresh();
      this.isLoginModalDisplayed = !this.user.current.isAuthenticated;
    }
  }

  loginExperienceLabel(le: LoginExperience) {
    return LoginExperience[le].toLowerCase()
  }
}

// react-ui/app/login.tsx
"use client";

import axios from "axios";
import getConfig from "next/config";
import { usePathname } from "next/navigation";
import { FormEvent, useEffect, useRef, useState } from "react";

enum LoginExperience {
  DEFAULT,
  IFRAME,
}

interface LoginOptionDto {
  label: string;
  loginUri: string;
  isSameAuthority: boolean;
}
async function getLoginOptions(): Promise<Array<LoginOptionDto>> {
  const response = await axios.get<Array<LoginOptionDto>>("/login-options");
  return response.data;
}

export default function LoginComponent() {
  const publicRuntimeConfig = getConfig();
  const [loginUri, setLoginUri] = useState("");
  const [selectedLoginExperience, setSelectedLoginExperience] = useState(
    LoginExperience.DEFAULT
  );
  const [isLoginModalDisplayed, setIsLoginModalDisplayed] = useState(false);
  const [isIframeLoginPossible, setIframeLoginPossible] = useState(false);
  const currentPath = usePathname();
  const iframeRef = useRef<HTMLIFrameElement>(null);

  useEffect(() => {
    fetchLoginOptions();

    const iframe = iframeRef.current;
    if (iframe) {
      iframe.src = "";
    }
    iframe?.addEventListener("load", onIframeLoad);
    return () => {
      iframe?.removeEventListener("load", onIframeLoad);
    };
  }, []);

  async function fetchLoginOptions() {
    const loginOpts = await getLoginOptions();
    if (loginOpts?.length < 1 || !loginOpts[0].loginUri) {
      setLoginUri("");
      setIframeLoginPossible(false);
    } else {
      setLoginUri(loginOpts[0].loginUri);
      setIframeLoginPossible(loginOpts[0].isSameAuthority);
    }
  }

  async function onSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    if (!loginUri) {
      return;
    }
    const formData = new FormData(event.currentTarget);
    const url = new URL(loginUri);
    url.searchParams.append(
      "post_login_success_uri",
      `${publicRuntimeConfig.baseUri}${currentPath}`
    );
    const loginUrl = url.toString();
    if (
      formData.get("selectedLoginExperience")?.toString() === "iframe" &&
      iframeRef.current
    ) {
      iframeRef.current.src = loginUrl;
      setIsLoginModalDisplayed(true);
    } else {
      window.location.href = loginUrl;
    }
  }

  function onIframeLoad(event: any) {
    if (!!event.currentTarget.src) {
      setIsLoginModalDisplayed(true);
    }
  }

  return (
    <form onSubmit={onSubmit}>
      <select
        value={selectedLoginExperience}
        onChange={(e) => {
          setSelectedLoginExperience(
            e?.target?.value === "iframe"
              ? LoginExperience.IFRAME
              : LoginExperience.DEFAULT
          );
        }}
      >
        {isIframeLoginPossible && (
          <option value={LoginExperience.IFRAME}>iframe</option>
        )}
        <option value={LoginExperience.DEFAULT}>default</option>
      </select>
      <button type="submit">Login</button>
      {isLoginModalDisplayed && <iframe ref={iframeRef}></iframe>}
    </form>
  );
}
